-- Canonical Postgres mirror schema (profile-agnostic).
--
-- This file mirrors what `SchemaGenerator.canonicalDDL` emits at runtime
-- and is checked in for documentation / manual bootstrap. Per-profile
-- embedding tables (`memory_embeddings_<profile>` with `vector(<dim>)`) are
-- generated by `SchemaGenerator.profileDDL(_:)` once the active backend's
-- dimension is discovered, so the mirror does not have to assume a fixed
-- dimension up front.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS memories (
    id UUID PRIMARY KEY,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    occurred_at TIMESTAMPTZ,
    source TEXT,
    conversation_id TEXT,
    language TEXT,
    sentiment DOUBLE PRECISION,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    search_document TSVECTOR,
    tombstoned BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS memories_occurred_at_idx ON memories (occurred_at DESC);
CREATE INDEX IF NOT EXISTS memories_created_at_idx  ON memories (created_at DESC);
CREATE INDEX IF NOT EXISTS memories_source_idx      ON memories (source);
CREATE INDEX IF NOT EXISTS memories_conversation_idx ON memories (conversation_id);
CREATE INDEX IF NOT EXISTS memories_search_doc_gin  ON memories USING GIN (search_document);

CREATE OR REPLACE FUNCTION memories_search_document_trigger() RETURNS trigger AS $$
BEGIN
    NEW.search_document :=
        setweight(to_tsvector('english', coalesce(NEW.text, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.source, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.conversation_id, '')), 'C');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS memories_search_document_update ON memories;
CREATE TRIGGER memories_search_document_update
    BEFORE INSERT OR UPDATE OF text, source, conversation_id ON memories
    FOR EACH ROW EXECUTE FUNCTION memories_search_document_trigger();

CREATE TABLE IF NOT EXISTS embedding_profiles (
    id           TEXT PRIMARY KEY,
    backend      TEXT NOT NULL,
    model_name   TEXT NOT NULL,
    dim          INTEGER NOT NULL,
    seq_len      INTEGER,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS entities (
    id UUID PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    entity_type    TEXT NOT NULL,
    aliases        JSONB NOT NULL DEFAULT '[]'::jsonb
);
CREATE INDEX IF NOT EXISTS entities_name_idx ON entities (canonical_name);
CREATE INDEX IF NOT EXISTS entities_type_idx ON entities (entity_type);

CREATE TABLE IF NOT EXISTS mentions (
    id           UUID PRIMARY KEY,
    memory_id    UUID NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    entity_id    UUID NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    start_offset INTEGER NOT NULL,
    end_offset   INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS mentions_memory_idx ON mentions (memory_id);
CREATE INDEX IF NOT EXISTS mentions_entity_idx ON mentions (entity_id);

CREATE TABLE IF NOT EXISTS relations (
    id                   UUID PRIMARY KEY,
    subject_entity_id    UUID NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    predicate            TEXT NOT NULL,
    object_entity_id     UUID NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    provenance_memory_id UUID NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS relations_subject_idx ON relations (subject_entity_id);
CREATE INDEX IF NOT EXISTS relations_object_idx  ON relations (object_entity_id);

CREATE TABLE IF NOT EXISTS tags (
    id   UUID PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS memory_tags (
    memory_id UUID NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    tag_id    UUID NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (memory_id, tag_id)
);

-- Example per-profile table (NOT executed; emitted dynamically by SchemaGenerator):
-- CREATE TABLE IF NOT EXISTS memory_embeddings_minilm_l6_v2 (
--     memory_id  UUID PRIMARY KEY REFERENCES memories(id) ON DELETE CASCADE,
--     embedding  VECTOR(384) NOT NULL,
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
-- );
-- CREATE INDEX IF NOT EXISTS memory_embeddings_minilm_l6_v2_hnsw_cosine
--     ON memory_embeddings_minilm_l6_v2 USING hnsw (embedding vector_cosine_ops);
